[package]
name = "yingting"
version = "0.1.0"
description = "婴听 - 汽车ECU开发工具"
authors = ["mozi"]
edition = "2021"

[lib]
name = "yingting_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"

[profile.release]
strip = true
lto = true
codegen-units = 1
