[package]
name = "peak"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi8", "dyn-symbols"] }
napi-derive = "3"
uuid = { version = "1", features = ["v4"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_LibraryLoader"] }
